import { AppError } from "./errors.js";
import type { PrDraft } from "./types.js";

const attributionPatterns = [
  /generated by/i,
  /created with/i,
  /co-authored-by:/i,
  /authored by ai/i,
];

export function validateDraft(draft: PrDraft): PrDraft {
  const title = draft.title.trim();
  const body = draft.body.trim();

  if (!title) {
    throw new AppError("Generated PR title was empty.");
  }

  if (!body) {
    throw new AppError("Generated PR body was empty.");
  }

  if (title !== title.toLowerCase()) {
    throw new AppError("Generated PR title must be lowercase.");
  }

  for (const pattern of attributionPatterns) {
    if (pattern.test(body)) {
      throw new AppError("Generated PR body included attribution text.");
    }
  }

  return { title, body };
}
